# Generated by Django 5.1.6 on 2025-02-12 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('path', models.ImageField(upload_to='captcha/alter_img/')),
                ('uuid_token', models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_captcha', models.BooleanField(default=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_captcha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captchas', to='captcha.captcha')),
                ('images', models.ManyToManyField(blank=True, related_name='captchas_images', to='captcha.captchaimg')),
            ],
        ),
    ]
